#
# Hooks that are run against every commit message after a user has written it.
#
CommitMsg:
  ALL:
    required: true

  HardTabs:
    enabled: true

  SingleLineSubject:
    enabled: true

#
# Hooks that are run after `git commit` is executed, before the commit message
# editor is displayed.
#
PreCommit:
  ALL:
    required: true

  BundleAudit:
    enabled: true

  BundleCheck:
    enabled: true

  LocalPathsInGemfile:
    enabled: true

  ExecutePermissions:
    enabled: true
    exclude:
      - bin/*

  Reek:
    enabled: true

  RuboCop:
    enabled: true

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true

  RailsBestPractices:
    enabled: true

  RailsSchemaUpToDate:
    enabled: true

#
# Hooks that are run before pushing changes
#
PrePush:
  ALL:
    required: true

  RSpec:
    enabled: true

  Brakeman:
    enabled: true
